<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="NUnit" Version="3.*" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.*" />
    <PackageReference Include="NUnit.Analyzers" Version="4.*" />
    <PackageReference Include="Moq" Version="4.*" />
    <PackageReference Include="FakeItEasy" Version="7.*" />
    <PackageReference Include="Shouldly" Version="4.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../FlockBuddy/FlockBuddy.csproj" />
  </ItemGroup>
</Project>
